# Generated by Django 5.2.6 on 2025-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsubmission',
            name='type',
            field=models.CharField(default='other', max_length=20),
            preserve_default=False,
        ),
    ]
